import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import JSZip from "jszip";
import { supabaseServer } from "../../../lib/supabase-server";

function safe(value: unknown) {
  return String(value ?? "").trim();
}

function titleCase(value: string) {
  return value.replace(/[_-]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

async function makePdf(templateName: string, record: Record<string, unknown>) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const name = safe(record.name) || "Recipient";

  page.drawText(templateName, { x: 55, y: 765, size: 24, font: bold, color: rgb(0.08, 0.08, 0.08) });
  page.drawText("Personalized Document", { x: 55, y: 735, size: 12, font, color: rgb(0.35, 0.35, 0.35) });
  page.drawText(`Dear ${name},`, { x: 55, y: 670, size: 16, font: bold });
  page.drawText("This document was generated automatically from your validated dataset.", { x: 55, y: 635, size: 11, font });

  let y = 585;
  for (const [key, value] of Object.entries(record)) {
    const text = `${titleCase(key)}: ${safe(value)}`;
    page.drawText(text.slice(0, 90), { x: 55, y, size: 11, font });
    y -= 24;
    if (y < 80) break;
  }

  page.drawText("Generated by DocFlow", { x: 55, y: 45, size: 9, font, color: rgb(0.45, 0.45, 0.45) });
  return pdf.save();
}

export async function POST(request: Request) {
  try {
    const { recordIds, templateId, templateName } = await request.json();
    if (!Array.isArray(recordIds) || recordIds.length === 0 || !templateId) {
      return NextResponse.json({ error: "recordIds and templateId are required." }, { status: 400 });
    }

    const { data: records, error } = await supabaseServer
      .from("uploaded_records")
      .select("id,row_data")
      .in("id", recordIds);
    if (error) throw error;

    const zip = new JSZip();
    for (const record of records ?? []) {
      const { data: job, error: jobError } = await supabaseServer
        .from("document_jobs")
        .insert({ record_id: record.id, template_id: templateId, status: "generating" })
        .select("id")
        .single();
      if (jobError) throw jobError;

      try {
        const bytes = await makePdf(templateName || templateId, record.row_data as Record<string, unknown>);
        const name = safe((record.row_data as Record<string, unknown>).name) || `record-${record.id.slice(0, 8)}`;
        zip.file(`${name}-${templateId}.pdf`, bytes);
        await supabaseServer.from("document_jobs").update({ status: "generated", completed_at: new Date().toISOString() }).eq("id", job.id);
      } catch (generationError) {
        await supabaseServer.from("document_jobs").update({ status: "failed", error_message: String(generationError) }).eq("id", job.id);
        throw generationError;
      }
    }

    const archive = await zip.generateAsync({ type: "uint8array" });
    return new Response(archive as BodyInit, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="docflow-${templateId}-documents.zip"`,
      },
    });
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: "PDF generation failed." }, { status: 500 });
  }
}
