const pages={
'/preview':['Data Preview','Review and validate the records before choosing a document template.'],
'/template':['Choose a Template','Select the document design and dynamic fields for your batch.'],
'/generate':['Generate Documents','Create personalized documents from your validated data.'],
'/email':['Prepare Email Campaign','Configure your message and recipients before sending.'],
'/tracking':['Tracking','Monitor generated documents and email delivery status.']};
import Link from 'next/link'; import {ArrowRight, CheckCircle2, Mail, FileText, Send, Download} from 'lucide-react';
export default function WorkflowPage({path}){let [title,desc]=pages[path]; let isPreview=path==='/preview';let isTemplate=path==='/template';let isGenerate=path==='/generate';let isEmail=path==='/email';let isTrack=path==='/tracking';return <div className="page"><div className="workflow"><b>{isPreview?'02':isTemplate?'03':isGenerate?'04':isEmail?'05':'06'} {title}</b><span>→</span><span>Workflow</span></div><section className="panel wide"><span className="pill">FRONTEND DEMO</span><h2>{title}</h2><p>{desc}</p>{isPreview&&<><div className="filebar"><b>students.xlsx</b><span>250 records • 4 columns</span><CheckCircle2 size={18}/><b>Validated</b></div><Table/></>}{isTemplate&&<div className="cards">{['Certificate','Offer Letter','Appointment Letter'].map((x,i)=><div className="template" key={x}><div className="template-preview"><FileText size={35}/><span>DOC-{String(i+1).padStart(2,'0')}</span></div><h3>{x}</h3><p>Clean professional layout with dynamic fields.</p><button>Select template <ArrowRight size={15}/></button></div>)}</div>}{isGenerate&&<div className="generate-box"><div className="big-icon"><FileText size={30}/></div><h3>Ready to generate 250 documents</h3><p>Template: Certificate • Source: students.xlsx</p><div className="progress"><i/></div><span>Preview mode — generation engine will be connected in Phase 2.</span><Link className="primary" href="/email">Continue <ArrowRight size={16}/></Link></div>}{isEmail&&<div className="email-layout"><div className="form"><label>From<input placeholder="you@company.com"/></label><label>Subject<input defaultValue="Your document is ready"/></label><label>Message<textarea defaultValue={'Hello {{name}},\n\nPlease find your personalized document attached.\n\nRegards,\nDocFlow Team'}/></label><Link className="primary" href="/tracking"><Send size={16}/> Prepare campaign</Link></div><div className="side-summary"><Mail size={28}/><h3>Campaign summary</h3><b>250</b><span>Recipients</span><b>250</b><span>Attachments</span></div></div>}{isTrack&&<><div className="stats compact"><div className="stat"><span>Sent</span><strong>210</strong></div><div className="stat"><span>Pending</span><strong>25</strong></div><div className="stat"><span>Failed</span><strong>15</strong></div></div><div className="tracking-table">{[['rahul@gmail.com','Certificate.pdf','Sent'],['priya@gmail.com','Certificate.pdf','Sent'],['arjun@gmail.com','Certificate.pdf','Failed'],['sai@gmail.com','Certificate.pdf','Pending']].map(r=><div className="track-row" key={r[0]}><b>{r[0]}</b><span>{r[1]}</span><strong className={r[2].toLowerCase()}>{r[2]}</strong><Download size={16}/></div>)}</div></>}</section></div>}
function Table(){return <div className="table">{[['#','Name','Email','Department'],['01','Rahul Sharma','rahul@example.com','ECE'],['02','Priya Reddy','priya@example.com','CSE'],['03','Arjun Kumar','arjun@example.com','EEE'],['04','Sai Teja','sai@example.com','ECE']].map((r,i)=><div className={i===0?'tr th':'tr'} key={i}>{r.map(c=><span key={c}>{c}</span>)}</div>)}</div>}
